name: Metrics
on:
  # Schedule daily updates
  # cron(Minutes Hours Day-of-month Month Day-of-week Year)
  schedule: [{cron: "0 9 * * MON"}]
  # Run workflow manually
  workflow_dispatch:
  # Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Base
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: StokicDusan
          template: "@classic"
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons
          plugin_topics_sort: stars

      - name: Side
        uses: lowlighter/metrics@latest
        with:
          filename: side.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: StokicDusan
          template: "@classic"
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
