name: Half-year-calendar
on:
  # Schedule daily updates
  # cron(Minutes Hours Day-of-month Month Day-of-week Year)
  schedule: [{cron: "0 9 * * TUE"}]
  # Run workflow manually
  workflow_dispatch:
  # Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          output_action: commit
          committer_branch: metrics-renders
          committer_message: "update calendar"
          filename: metrics-isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
