name: Half-year calendar
on:
  # Schedule daily updates
  # cron(Minutes Hours Day-of-month Month Day-of-week Year)
  schedule: [{cron: "0 9 * * TUE"}]
  # Run workflow manually
  workflow_dispatch:
  # Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
uses: StokicDusan/metrics@latest
with:
  filename: metrics-isocalendar.svg
  token: ${{ secrets.METRICS_TOKEN }}
  base: ""
  plugin_isocalendar: yes