name: Metrics
on:
  # Schedule daily updates
  # cron(Minutes Hours Day-of-month Month Day-of-week Year)
  schedule: [{cron: "0 9 * * MON"}]
  # Run workflow manually
  workflow_dispatch:
  # Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Base
        uses: lowlighter/metrics@latest
        with:
          filename: assets/github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: StokicDusan
          plugin_languages: yes
          plugin_languages_ignored: html, scss, css, tex, less, dockerfile, batchfile, makefile, qmake, lex, cmake, gnuplot, vue, scala, ejs
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 10
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons
          plugin_topics_sort: stars

      - name: Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: assets/iso_calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: StokicDusan
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
      - name: With worldmap
        uses: lowlighter/metrics@latest
        with:
          filename: assets/stargazers-worldmap.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts: no
          plugin_stargazers_worldmap: yes
          plugin_stargazers_worldmap_token: ${{ secrets.GOOGLE_MAP_TOKEN }}
          plugin_stargazers_worldmap_sample: 200
