name: Metrics
on:
  # Schedule daily updates
  # cron(Minutes Hours Day-of-month Month Day-of-week Year)
  schedule: [{cron: "0 9 * * MON"}]
  # Run workflow manually
  workflow_dispatch:
  # Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: StokicDusan/metrics@latest
        with:
          output_action: commit
          committer_branch: metrics-renders
          committer_message: "update metrics"
          token: ${{ secrets.METRICS_TOKEN }}
